# Generated by Django 5.0.1 on 2024-01-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='catgory',
            new_name='category',
        ),
    ]
